### ISSUE TITLE
Dependency Specifications

### ISSUE THREAD

**Issue by TimBailey-pnk** [grofit/treacherous-aurelia#11]
Hi,
Having an issue JSPM install npm:treacherous-aurelia with dependency errors.
Currently they are defined as (ie .*)
```
"dependencies": {
      "aurelia-framework": "^1.0.1",
      "event-js": "0.1.*",
      "property-resolver": "0.0.*",
      "treacherous": "0.12.*"
}
```

Based on this, https://gist.github.com/hmps/995583ff1c8755d5f795, I've adjusted the dependency defs to below and now seems to work.  Did I miss something?
```
"dependencies": {
      "aurelia-framework": "^1.0.1",
      "event-js": "0.1",
      "property-resolver": "0.0",
      "treacherous": "0.12"
 }
```

I can create a PR if required.

**Comment by grofit** [comment]
If the latter works feel free to raise a PR, the problem I had historically (with NPM) was that when I did `^0.1.0` for event-js or whatever the lib was it wouldnt pick up double digits for the revision, so `0.1.10` would not get picked up, `0.1.9` would be the last version matched by the semver, so the star was introduced to allow anything in the last field.

Anyway if that works and pulls in the right versions (as JSPM semver resolution is slightly different to NPM) then raise a PR and I will get it included.

**Comment by grofit** [comment]
Marking this as closed as I assume its all working now
